# Generated by Django 2.1.5 on 2019-10-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('account', '0001_initial'),
        ('delivery_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelevaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver_profile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_service.delivery_product')),
            ],
        ),
    ]
